### ISSUE TITLE
skill issue from my part

### ISSUE THREAD

**Issue by DarkReaperBoy** [Nenotriple/R-ESRGAN-AnimeVideo-UI#1]

**Comment by DarkReaperBoy** [comment]
hello, where is the source code?

**Comment by Nenotriple** [comment]
My script has always been available as plain text.
- https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/blob/main/R-ESRGAN-AnimeVideo-UI.pyw

All other files are provided as exact copies of the original from their respective authors linked in the credits section of the readme.

**Comment by DarkReaperBoy** [comment]
apologies 🙏
