### ISSUE TITLE
Feature Addition - Support more than just the built in upscale models

### ISSUE THREAD

**Issue by SaturnRingssss** [Nenotriple/R-ESRGAN-AnimeVideo-UI#11]
One thing I noticed after adding my own converted models to the model folder is that the program does not list or show the new ones
when I go to process a video it just shows the stock ones.  So I renamed my model as an experiment to match one of the existing models in the program folder and replaced it with my own and worked like a charm.  

So it would be great if I could add new models to the folder and just select which one I wish to use as an optional model via the GUI

Thanks again.

**Comment by Nenotriple** [comment]
I will look into this. Could you please upload the converted model here?

**Comment by SaturnRingssss** [comment]
I quickly grabbed a couple of pytorch models off of OpenModelDB and used chaiNNer to convert just as a fast experiment to see if it was possible.  I only got as far as starting the upscaling process after extracting to see if the program would crash or not.  The program was processing as fps was indicating different counts for the models I converted.  I never let the program complete to see the finished result as I just wanted see if it was possible.

**Comment by Nenotriple** [comment]
Ok, no problem. I'll mess with it sometime later.

I think I tried that long before I made the app and it was "working", but the output was all jumbled. The image was being upscaled, but each "tile" wasn't being correctly positioned afterwards. Could have been an error on my part though.

The changes are almost ready, just tweaking some things. I also set up a way to create a sample by extracting a 5 second clip from the center of the selected video. So now you can test the output on longer videos much faster. And some other little additions.

**Comment by SaturnRingssss** [comment]
Okay, sounds good.

**Comment by Nenotriple** [comment]
In [v1.16](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/releases/tag/v1.16), the app now looks for new models in the `bin\models` folder.

It was only tested by renaming an existing model to something else. As long as the model is converted with proper instructions ".praram file", then I guess it should work. Eventually I'll try converting some models, but if you get something working please let me know. 

Thanks for the suggestion, don't hesitate to drop in again if you think of anything else.

**Comment by SaturnRingssss** [comment]
Sounds Great.

Thanks Again.
