### ISSUE TITLE
why this gui only use CPU to do all thing

### ISSUE THREAD

**Issue by jiajet** [Nenotriple/R-ESRGAN-AnimeVideo-UI#13]
I tried to use this software last time but I founded it only use my CPU but not using my GPU at all can someone tell me why?

**Comment by Nenotriple** [comment]
Without more information about your hardware or the exact process you tried, I can't really provide any help.

Though maybe I should point out that only upscaling is done with the GPU, all other operations (extract frames, merge, resize, etc.) are done with the CPU.
