### ISSUE TITLE
Error Found - Failed to download 'ffmpeg-6.0-essentials_build.zip'

### ISSUE THREAD

**Issue by Jay123210599** [Nenotriple/R-ESRGAN-AnimeVideo-UI#14]
When I tried opening the tool, I got this. Can someone help me?
![Screenshot (524)](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/141977822/20ed86df-25b9-4b33-841d-6c622eeb8cd8)

**Comment by Nenotriple** [comment]
Thank you for bringing this to my attention! It looks like ffmpeg is no longer hosting `ffmpeg-6.0-essentials_build.zip`. I've had to deal with these sort of issues several times so I'm just going to bundle everything in the release package.

Give the [latest release](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/releases?q=executable&expanded=true) a try and let me know if it works.
