### ISSUE TITLE
Does not use [display width] and [display height] header info (mkv), resulting the output to look stretched.

### ISSUE THREAD

**Issue by klaritan** [Nenotriple/R-ESRGAN-AnimeVideo-UI#15]
Some anime DVD releases come within a mkv container with a video track that has different pixel width and display width.

R-ESRGAN-AnimeVideo-UI seems to use pixel width and display, which results a weird aspect ratio.

**Comment by Nenotriple** [comment]
I'll need a copy of the video, or a similar video, to be able to test this issue.

Do you know where I can find a video like this?

Could you please provide the ffprobe output for this video?

```
1. Go to the video you're having issues with, Shift+Right-Click it and select : Copy as path

2. Go to: R-ESRGAN-AnimeVideo-UI\bin

3. Shift+Right-Click in the folder and select: Open PowerShell window here

4. In the PowerShell window type: ./ffprobe then paste the video path. 

5. Press enter then copy the results of the terminal and paste them here.
```
