### ISSUE TITLE
Not all frames are extracted

### ISSUE THREAD

**Issue by klaritan** [Nenotriple/R-ESRGAN-AnimeVideo-UI#16]
R-ESRGAN-AnimeVideo-UI properly recognizes the number of frames (37k), but only extracts around 11k frames.

Video is AVC1 24 bits, at 23.967fps inside mkv.

**Comment by Nenotriple** [comment]
Just like the other issue you've posted, this is difficult to troubleshoot without being able to reproduce it. If you could follow these steps then I might get a better idea of what's happening.

1. Go to the video you're having issues with, Shift+Right-Click it and select : `Copy as path`

2. Go to: `R-ESRGAN-AnimeVideo-UI\bin`

3. Shift+Right-Click in the folder and select: `Open PowerShell window here`

4. In the PowerShell window type: `./ffprobe` then paste the video path. 

5. Press enter then copy the results of the terminal and paste them here.

Is this same video triggering both of the issues you've posted?

If you could provide a copy of the video you're having the problem with would be best.
