### ISSUE TITLE
GPU acceleration support

### ISSUE THREAD

**Issue by shahbazmansahia** [Nenotriple/R-ESRGAN-AnimeVideo-UI#18]
I've been trying to upscale a video and looked at the code. I am unable to find any support/selector that allows me to use local GPU hardware to further speed up the process. Currently, from what I could see, it only has CPU-thread support. The vulkan app picks up the hardware but doesn't really use the more powerful GPU (the one connected via thunderbolt) nor does it give me an option to do that. Please let me know if I'm missing something. Thanks.

**Comment by Nenotriple** [comment]
If you're referring to extracting/merging/resizing, etc., then yeah, it's all CPU. The only thing the GPU's responsible for in this app is upscaling, and this code doesn't actually touch the GPU at all, it's all handled though R-ESRGAN.

---

If you're referring to upscaling...

There's really only one thing I can think of.  R-ESRGAN supports this option:

    -g gpu-id  :  gpu device to use (default=auto) can be 0,1,2 for multi-gpu

You can add the parameter to this line where REALESRGAN is called for upscaling the video frames: https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/blob/f2177fd604e4751892dbbf1476a8b186d39e4610/R-ESRGAN-AnimeVideo-UI.py#L1179

Add the parameter to the command like this: 

    self.process = subprocess.Popen([REALESRGAN, "-i", "raw_frames", "-o", "upscaled_frames", "-n", self.upscale_model.get(), "-s", self.scale_factor.get(), "-f", "jpg", "-g", "0"], creationflags=subprocess.CREATE_NO_WINDOW)

You could also simply try using R-ESRGAN from the command line, the files are already downloaded with the repo, see the [instructions.](https://github.com/xinntao/Real-ESRGAN?tab=readme-ov-file#usage-of-portable-executable-files) This would let you test the arguments a little easier.

Please let me know if that works for you, I guess I should add a way to adjust that.

---

### Closing: Open a new issue if you'd like to troubleshoot
