### ISSUE TITLE
Issue: Upscaled Video File Not Generated After Merging Frames

### ISSUE THREAD

**Issue by Sxrjs2010** [Nenotriple/R-ESRGAN-AnimeVideo-UI#2]
Firstly, I would like to express my gratitude for your work on this project. Thank you for your efforts in providing such a useful tool.

I used your project to perform video upscaling, and after clicking "Merge frames," the console displays "Done Merging!" but the PandaDrivingCar_UPSCALE.mp4 file is not generated.

Steps Taken:

I have successfully installed and executed your project.
Both raw_frames and upscaled_frames directories have been generated with the corresponding images.
After clicking "Merge frames," the console displayed the following information:
PandaDrivingCar.mp4
Output: D:/Self/AI/R-ESRGAN-AnimeVideo-UI-main\PandaDrivingCar_UPSCALE.mp4
Done Merging!

Environment Information:

Operating System: Windows 11
Python Version: [3.10.8]
![upscaled_frames](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/137243324/f06dd7a4-006a-4d96-9554-ae5136d19698)
![merged_frames](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/137243324/310fed79-514a-4263-b6a0-3cd4fd9c50a7)
![NoUpscaledVideo](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/137243324/828e2f32-1585-45f9-85f3-96b19d3b1b6d)

I want to thank you once again for your work on this project, and any guidance on resolving this issue would be greatly appreciated.

**Comment by Nenotriple** [comment]
Thank you so much for the kind words!

I'm having trouble reproducing the issue, could you upload the video file here?

1) Are you using a different scaling factor? x2 (default), x3, x4

2) Are you scaling the frames back down after upscaling?

3) Does it still fail if you simply go through the numbered steps, without pressing any other buttons at all?

You can also try out [the latest v1.09 release.](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/releases/tag/v1.09)

I didn't make any specific changes related to this issue, but I did rewrite some of the merge operation, it's possible it might just work now. 🤞

Is this an issue with all files? Could you test with this video?

https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/70049990/1b44077b-952b-4622-85b1-12fee545e437

**Comment by Sxrjs2010** [comment]
Surprised, after merging the sample video you provided, I can generate sample_original_UPSCALE.mp4. It might be an issue with my video. I'll upload the video, and I'd appreciate it if you could take a look when you have time.

https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/137243324/ba3da311-5567-4acb-95f3-db18357e6325

**Comment by Sxrjs2010** [comment]
i've tried v1.09 release and promblem resolved.
thanks a lot.
![resolved](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/137243324/cba86cc1-112e-465a-b5db-41dda2391175)

**Comment by Nenotriple** [comment]
> i've tried v1.09 release and problem resolved. thanks a lot.

I'm really glad it's working for you. Don't hesitate to drop in with any suggestions or bug reports!
