### ISSUE TITLE
Unhandled Exception in Script Error

### ISSUE THREAD

**Issue by SaturnRingssss** [Nenotriple/R-ESRGAN-AnimeVideo-UI#9]
I had this issue when opening UI in windows 10 after clicking Yes following the prompt for downloading the additional files.

![Error](https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/assets/153692245/a20f3d9a-de64-4678-ac17-6a88ad0f636c)

**Comment by Nenotriple** [comment]
Thank you for reporting this.

The collect_requirements script was very messy and I'm going to rewrite it. It shouldn't take long.

In the meantime you can download the files manually.

- https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-windows.zip
   - bin\realesrgan-ncnn-vulkan.exe
   - bin\vcomp140d.dll
   - bin\vcomp140.dll
   - bin\models\realesr-animevideov3-x2.bin
   - bin\models\realesr-animevideov3-x3.bin
   - bin\models\realesr-animevideov3-x4.bin
   - bin\models\realesr-animevideov3-x2.param
   - bin\models\realesr-animevideov3-x3.param
   - bin\models\realesr-animevideov3-x4.param

- https://github.com/Nenotriple/R-ESRGAN-AnimeVideo-UI/tree/main/bin/models
 - These models are optional.


- https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-essentials_build.zip
  - bin/ffmpeg.exe
  - bin/ffprobe.exe

**Comment by SaturnRingssss** [comment]
Great Thanks

**Comment by Nenotriple** [comment]
This should be fixed with the latest release. ( I updated v1.15 )

Thank you again for reporting the issue.

Please let me know if it works for you.

**Comment by SaturnRingssss** [comment]
You bet, the fix in the latest version did the trick.  Thanks.

I also followed your previous instructions and also was successful as well.

**Comment by Nenotriple** [comment]
Perfect!
